### ISSUE TITLE
passwordlist

### ISSUE THREAD

**Issue by Knrd2** [Stephin-Franklin/Hack-Insta#1]
Hi, im trying your program for the first time. Do i have to create an own password list or can i just use an existing one? 
Best

**Comment by Knrd2** [comment]
**The program doesn't start (with proxy):** 

[*] 4 Passwords loads successfully
[*] Do you want to use proxy (y/n): y

[*] Check new ip...
[*] Can't reach proxy "149.56.81.59"

[*] Please add delay between the bruteforce action (in seconds): 40

Traceback (most recent call last):
  File "hackinsta.py", line 161, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 113, in Login
    r = sess.get('https://www.instagram.com/') 
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff031fe55d0>: Failed to establish a new connection: [Errno 111] Connection refused',)))



**(without proxy):** 
[*] 4 Passwords loads successfully
[*] Do you want to use proxy (y/n): n
[*] Please add delay between the bruteforce action (in seconds): 40

Traceback (most recent call last):
  File "hackinsta.py", line 161, in <module>
    sess = instabrute.Login(password)
  File "hackinsta.py", line 114, in Login
    sess.headers.update({'X-CSRFToken' : r.cookies.get_dict()['csrftoken']})
KeyError: 'csrftoken'

**Comment by Anas289** [comment]
@

**Comment by iAkashPattnaik** [comment]
u can use premium proxies to get rid of this error

**Comment by sankopay** [comment]
@BLUE-DEVIL1134 

how to solve this issue?? please help its so important

ProxyError: HTTPSConnectionPool(host='www.instagram.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D3E07D7240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

**Comment by sankopay** [comment]
@BLUE-DEVIL1134 i used premium external proxies still not working could you please guide me through it??? it's really important please

**Comment by iAkashPattnaik** [comment]
its a bug
the proxy should be used as a dict with both `http` and `https`

**Comment by sankopay** [comment]
could you please help me throught it? @BLUE-DEVIL1134  it's not the proxy error, i really wanna have to get this account would you please help me

**Comment by iAkashPattnaik** [comment]
as much as i know
instagram has changed the headers and post data
so its hard for now
